name: project-1

on: workflow_dispatch

env:
  IMAGE_NAME: odlotdevsecops/demo-app
  IMAEG_TAG: juice-shop-1.0

jobs:
  yarn_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: juice-shop
    container:
      image: node:18-bullseye
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Install package dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  build_image:
    needs: yarn_test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: juice-shop
          push: true
          tags: $IMAGE_NAME:$IMAGE_TAG
